name: Publish Package

on:
    workflow_dispatch:
    pull_request:
        types: [closed]
        branches:
            - main

jobs:
    publish:
        runs-on: ubuntu-latest
        if: |
            github.event_name == 'workflow_dispatch' ||
            (github.event_name == 'pull_request' && github.event.action == 'closed' &&
                github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main')
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.10.13

            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install tox

            - name: Publish Package
              run: |
                  echo $PROD_PYPI_TOKEN
                  tox -e publish
              env:
                  PROD_PYPI_TOKEN: ${{ secrets.PROD_PYPI_TOKEN }}
